In [1]:
import pandas as pd
import numpy as np
import pickle as pk

In [2]:
f = open('rt.pk', 'rb')
rt = pk.load(f)
f = open('tp.pk', 'rb')
tp = pk.load(f)

In [3]:
np.array(rt).shape, np.array(tp).shape

((339, 5825), (339, 5825))

In [4]:
none_interact = (np.array(rt) == -1).sum()
print(339 * 5825 - none_interact, none_interact)

1873838 100837


In [5]:
none_interact = (np.array(tp) == -1).sum()
print(339 * 5825 - none_interact, none_interact)

1831253 143422


In [6]:
user = pd.read_csv('userlist_idx.csv')
item = pd.read_csv('wslist_idx.csv')

In [7]:
user.head()

Unnamed: 0  [User ID]  [IP Address]  [Country]  [IP No.]  [AS]  [Latitude]  \
0           0          0           278          1         0   135     38.0000   
1           1          1           106          1         0   135     38.0464   
2           2          2           292         17         0    13     35.6850   
3           3          3            22          1         1    61     40.4249   
4           4          4            78          1         1    61     40.4249   

   [Longitude]  
0     -97.0000  
1    -122.2300  
2     139.7514  
3     -86.9162  
4     -86.9162

In [8]:
item.head()

Unnamed: 0  Unnamed: 0.1  [Service ID]  \
0           0             0             0   
1           1             1             1   
2           2             2             2   
3           3             3             3   
4           4             4             4   

                                      [WSDL Address]  [Service Provider]  \
0  http://ewave.no-ip.com/ECallws/CinemaData.asmx...                2281   
1  http://ewave.no-ip.com/ECallws/StadiumSinchron...                2281   
2  http://ewave.no-ip.com/EcallWS/CinemaSinchroni...                2281   
3  http://ewave.no-ip.com/ECallws/StadiumData.asm...                2281   
4  http://ewave.no-ip.com/ECallws/BuyerData.asmx?...                2281   

   [IP Address]  [Country]  [IP No.]  [AS]  [Latitude]  [Longitude]  
0          1122          1         0  1263        38.0        -97.0  
1          1122          1         0  1263        38.0        -97.0  
2          1122          1         0  1263        38.0        -97.0  
3          1122          1         0  1263        38.0        -97.0  
4          1122          1         0   185        38.0        -97.0

In [9]:
# 打乱数组
def shuffle_array(data):
    data = np.array(data)
    idx = np.random.permutation(data.shape[0])
    data = data[idx]
    return data

In [10]:
user = shuffle_array(user)
user = user.tolist()
user

[[152.0, 152.0, 45.0, 18.0, 1.0, 95.0, 49.2333, 7.0],
 [297.0, 297.0, 215.0, 6.0, 2.0, 27.0, -25.4167, -49.25],
 [231.0, 231.0, 205.0, 1.0, 1.0, 21.0, 37.4178, -122.172],
 [158.0, 158.0, 150.0, 24.0, 1.0, 39.0, 25.0392, 121.525],
 [157.0, 157.0, 93.0, 24.0, 1.0, 39.0, 25.0392, 121.525],
 [235.0, 235.0, 110.0, 18.0, 2.0, 95.0, 51.7167, 8.7667],
 [219.0, 219.0, 51.0, 1.0, 1.0, 59.0, 40.5032, -74.4289],
 [294.0, 294.0, 154.0, 1.0, 2.0, 6.0, 38.6071, -121.4633],
 [57.0, 57.0, 44.0, 1.0, 1.0, 96.0, 32.9482, -96.7297],
 [288.0, 288.0, 305.0, 1.0, 2.0, 40.0, 43.0761, -89.4104],
 [289.0, 289.0, 172.0, 1.0, 2.0, 40.0, 43.0761, -89.4104],
 [107.0, 107.0, 248.0, 1.0, 1.0, 23.0, 28.5663, -81.2608],
 [266.0, 266.0, 211.0, 27.0, 2.0, 25.0, 48.86, 2.35],
 [217.0, 217.0, 243.0, 19.0, 1.0, 86.0, -34.8581, -56.1708],
 [150.0, 150.0, 229.0, 18.0, 1.0, 95.0, 49.2333, 7.0],
 [116.0, 116.0, 317.0, 18.0, 1.0, 81.0, 47.6667, 9.1833],
 [187.0, 187.0, 331.0, 3.0, 1.0, 133.0, 37.9833, 23.7333],
 [204.0, 204.0, 8

In [11]:
# shard_k = 10
# shard_t = rt.shape[0] * rt.shape[1] / shard_k

In [12]:
def check_len(data):
    ans = []
    for i in range(len(data)):
        ans.append(len(data[i]))
    return ans

In [13]:
a = {}
for i in range(339):
    a[i] = rt[i]

In [14]:
a[0][0]

5.982

In [15]:
data = []
for i in a:
    for j in a[i]:
        data.append([i, j]) #i与全部的交互数据 rt[i][j]都被存了起来
np.array(data).shape

(1974675, 2)

In [16]:
from datasets.data_partition import *
# SISA
C, users, items = data_partition_3(a, 10)

In [17]:
n_C = []
for i in range(len(C)):
    t = 0
    for j in C[i]:
        t += len(C[i][j])
    n_C.append(t)

In [18]:
print(339 * 5825)
print(n_C)

1974675
[197467, 197468, 197467, 197468, 197467, 197468, 197467, 197468, 197467, 197468]


In [19]:
print(check_len(C))
print(check_len(users))
print(check_len(items))

[339, 339, 339, 339, 339, 339, 339, 339, 339, 339]
[339, 339, 339, 339, 339, 339, 339, 339, 339, 339]
[9570, 9559, 9640, 9508, 9571, 9602, 9563, 9564, 9518, 9528]


In [20]:
C
# print(C[0][158])
for i in C[0]:
    print(len(C[0][i]))

641
582
561
595
541
579
606
577
533
617
559
583
564
587
572
563
574
587
515
604
586
573
567
585
572
575
574
600
595
567
591
573
577
582
572
561
572
573
593
595
584
568
615
580
584
561
575
576
598
579
564
564
550
624
587
632
577
614
571
576
580
596
624
579
593
603
595
597
608
558
630
619
600
615
544
563
557
548
584
581
590
566
595
585
585
556
596
569
570
627
609
597
551
616
579
632
601
602
550
568
591
512
612
585
589
607
605
558
612
569
577
628
603
592
602
598
560
623
568
622
556
579
572
575
571
581
558
580
566
576
584
596
606
584
615
552
534
586
541
617
602
632
625
618
575
576
517
543
559
618
543
611
598
619
572
576
582
593
562
604
556
574
604
555
609
623
592
594
564
551
575
593
566
551
572
594
605
540
559
582
568
609
595
583
565
566
606
581
630
589
582
570
579
645
629
557
560
601
631
615
551
595
536
550
573
554
561
623
576
605
630
563
571
544
563
580
565
599
546
588
556
572
551
601
568
608
656
543
595
544
599
565
576
568
595
610
593
599
560
590
611
587
564
577
599
605
586
590
587
524


In [21]:
a = []

In [22]:
a += [1, 2]
a

[1, 2]

In [23]:
f = open('C_U_type-3_num-10.pk', 'rb')
df = pk.load(f)
df

[[173,
  137,
  131,
  291,
  319,
  138,
  272,
  56,
  179,
  328,
  99,
  316,
  309,
  289,
  53,
  52,
  164,
  240,
  199,
  261,
  259,
  271,
  106,
  217,
  298,
  197,
  114,
  172,
  54,
  33,
  70,
  87,
  247,
  59,
  30,
  335,
  257,
  278,
  169,
  181,
  63,
  153,
  310,
  159,
  143,
  270,
  134,
  292,
  41,
  58,
  302,
  260,
  111,
  115,
  135,
  211,
  202,
  45,
  198,
  283,
  220,
  177,
  25,
  315,
  241,
  306,
  232,
  7,
  68,
  266,
  245,
  69,
  209,
  1,
  256,
  102,
  140,
  73,
  269,
  213,
  152,
  334,
  279,
  18,
  82,
  243,
  180,
  57,
  141,
  167,
  239,
  22,
  185,
  78,
  190,
  189,
  194,
  72,
  23,
  210,
  320,
  94,
  273,
  244,
  275,
  313,
  207,
  296,
  130,
  35,
  332,
  265,
  28,
  26,
  333,
  165,
  195,
  248,
  109,
  86,
  233,
  312,
  286,
  318,
  5,
  49,
  47,
  60,
  61,
  314,
  147,
  12,
  88,
  317,
  119,
  125,
  129,
  182,
  2,
  284,
  20,
  294,
  305,
  280,
  218,
  308,
  299,
  91,
  229,
  2

In [30]:
f = open('rt.pk', 'rb')
data = pk.load(f)
np.nonzero(data)

(array([  0,   0,   0, ..., 338, 338, 338], dtype=int64),
 array([   0,    1,    2, ..., 5822, 5823, 5824], dtype=int64))

In [40]:
index = np.transpose(np.nonzero(np.array(data).reshape(3, -1, 5)))
index

array([[     0,      0,      0],
       [     0,      0,      1],
       [     0,      0,      2],
       ...,
       [     2, 131644,      2],
       [     2, 131644,      3],
       [     2, 131644,      4]], dtype=int64)

In [26]:
import numpy as np
a = np.random.random(100)
quantile = np.percentile(a, q = 99)
