In [2]:
import numpy as np

In [69]:
tensor = np.random.random((6, 6)) * 2
mask = np.random.rand(*tensor.shape).astype('float32')  # [0, 1]

mask[mask > (13 / 36)] = 1
mask[mask < (13 / 36)] = 0
train_Tensor = tensor * (1 - mask)
train_Tensor

array([[1.4619072 , 0.        , 0.24630502, 1.32725094, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.7486986 , 1.41334293,
        1.12131072],
       [0.        , 1.05158462, 1.20227053, 0.        , 1.26396069,
        0.        ],
       [0.        , 1.24007803, 0.        , 0.31973502, 0.        ,
        1.87636064],
       [0.        , 0.        , 1.43260334, 1.1603961 , 0.30951022,
        0.        ],
       [0.83409965, 0.        , 0.11625911, 0.        , 0.        ,
        0.        ]])

In [71]:
tensor = np.random.random((6, 6)) * 2
mask = np.random.rand(*tensor.shape).astype('float32')  # [0, 1]

mask[mask > (12 / 36)] = 1
mask[mask < (12 / 36)] = 0
train_Tensor = tensor * (1 - mask)
train_Tensor

array([[0.44576808, 0.        , 1.34949148, 0.        , 0.        ,
        0.26591249],
       [0.        , 0.        , 1.21240792, 1.35709601, 1.40629016,
        0.        ],
       [0.        , 0.        , 0.        , 0.77379227, 0.        ,
        0.20574211],
       [1.00083021, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 1.76740252, 0.        ,
        1.45533573],
       [0.        , 1.29356373, 0.95267563, 1.26563092, 0.21079338,
        0.        ]])

In [72]:
tensor = np.random.random((6, 6)) * 2
mask = np.random.rand(*tensor.shape).astype('float32')  # [0, 1]

mask[mask > (12 / 36)] = 1
mask[mask < (12 / 36)] = 0
train_Tensor = tensor * (1 - mask)
train_Tensor

array([[0.        , 0.        , 0.        , 1.03102806, 0.        ,
        0.        ],
       [1.91207654, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.82624302, 0.        , 0.        ,
        0.        ],
       [1.82164679, 0.        , 0.        , 0.        , 1.85418165,
        0.        ],
       [0.35850318, 0.        , 0.        , 0.        , 0.11656229,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.72836567]])

In [73]:
tensor = np.random.random((6, 6)) * 2
mask = np.random.rand(*tensor.shape).astype('float32')  # [0, 1]

mask[mask > (12 / 36)] = 1
mask[mask < (12 / 36)] = 0
train_Tensor = tensor * (1 - mask)
train_Tensor

array([[1.76475414, 0.38735686, 0.71882408, 0.        , 0.        ,
        0.        ],
       [0.91329065, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.65570254],
       [0.        , 1.7592089 , 0.25554474, 0.        , 0.        ,
        1.75362237],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.08035434, 0.        , 1.47174092,
        0.        ]])