In [1]:
import numpy as np

In [4]:
a = np.random.random((3, 4))
a

array([[0.57138457, 0.13293538, 0.95760812, 0.23372391],
       [0.73241212, 0.68116427, 0.28021395, 0.74534072],
       [0.89613137, 0.70977172, 0.109313  , 0.64525153]])

In [5]:
b = [1, 2, 1]
c = np.zeros((3, 4))
c = a[b]
c

array([[0.73241212, 0.68116427, 0.28021395, 0.74534072],
       [0.89613137, 0.70977172, 0.109313  , 0.64525153],
       [0.73241212, 0.68116427, 0.28021395, 0.74534072]])

In [14]:
li = []
for i in range(len(c)):
    li.append(c[i])
li

[array([0.73241212, 0.68116427, 0.28021395, 0.74534072]),
 array([0.89613137, 0.70977172, 0.109313  , 0.64525153]),
 array([0.73241212, 0.68116427, 0.28021395, 0.74534072])]

In [18]:
np.stack(c, axis = 0)


array([[0.73241212, 0.68116427, 0.28021395, 0.74534072],
       [0.89613137, 0.70977172, 0.109313  , 0.64525153],
       [0.73241212, 0.68116427, 0.28021395, 0.74534072]])

# Author: Yuxiang Zeng

# Method : Ours    Idea新尝试

## Dataset : rt

# Desity = 0.10

In [1]:
!python Experiment.py --dataset rt --interaction NeuCF --rounds 1 --agg_epochs 5 --density 0.10 --part_type 5 --debug 1 --agg_function 3

2023-01-17 15:26:43  Namespace(agg2=1, agg_epochs=5, agg_function=3, agg_type='softmax', balance=0, batch_size=128, beta=1, cluster='deep', cuda=True, dataset='rt', debug=1, density=0.1, devices='gpu', dimension=32, dir='../Dataset/mnist', dropout=0.1, epoch=1500, hidden_dims=[64, 64, 100], input_dim=128, interaction='NeuCF', kmeans_type=1, lamda=1, latent_dim=10, log_interval=100, lr=0.0001, n_classes=10, n_clusters=10, n_jobs=1, node2vec=0, node2vec_batchsize=32, node2vec_dim=128, node2vec_epochs=20, node2vec_length=8, node2vec_walk=15, node2vec_windows=3, num_layers=2, order=2, part_iter=50, part_type=5, path='./datasets/data/WSDREAM/', pre_epoch=1000, pretrain=True, processed=0, retrain=0, rounds=1, save_model=1, slice_epochs=60, slices=10, subagg=1, verbose=10, wd=0.0005)
2023-01-17 15:26:43  Experiment start!
2023-01-17 15:26:43  Dataset : rt     interaction : NeuCF
2023-01-17 15:26:43  Density : 10.00%, slice_epochs : 100, agg_epochs : 5
2023-01-17 15:26:43  Part_type : 5,    sl

In [2]:
!python Experiment.py --dataset rt --interaction CSMF --rounds 1 --agg_epochs 10 --density 0.10 --part_type 5 --debug 1 --agg_function 3

usage: Experiment.py [-h] [--path [PATH]] [--dataset DATASET]
                     [--interaction INTERACTION] [--rounds ROUNDS]
                     [--slice_epochs SLICE_EPOCHS] [--agg_epochs AGG_EPOCHS]
                     [--batch_size BATCH_SIZE] [--verbose VERBOSE]
                     [--devices DEVICES] [--save_model SAVE_MODEL]
                     [--debug DEBUG] [--processed PROCESSED]
                     [--retrain RETRAIN] [--slices SLICES]
                     [--part_type PART_TYPE] [--part_iter PART_ITER]
                     [--density DENSITY] [--dropout DROPOUT]
                     [--dimension DIMENSION] [--order ORDER]
                     [--num_layers NUM_LAYERS] [--node2vec NODE2VEC]
                     [--node2vec_batchsize NODE2VEC_BATCHSIZE]
                     [--node2vec_walk NODE2VEC_WALK]
                     [--node2vec_dim NODE2VEC_DIM]
                     [--node2vec_epochs NODE2VEC_EPOCHS]
                     [--node2vec_length NODE2VEC_LENGTH]

In [3]:
!python Experiment.py --dataset rt --interaction Pure_Mf --rounds 1 --agg_epochs 10 --density 0.10 --part_type 5 --debug 1 --agg_function 3

2023-01-17 15:39:47  Namespace(agg2=1, agg_epochs=10, agg_function=3, agg_type='softmax', balance=0, batch_size=128, beta=1, cluster='deep', cuda=True, dataset='rt', debug=1, density=0.1, devices='gpu', dimension=32, dir='../Dataset/mnist', dropout=0.1, epoch=1500, hidden_dims=[64, 64, 100], input_dim=128, interaction='Pure_Mf', kmeans_type=1, lamda=1, latent_dim=10, log_interval=100, lr=0.0001, n_classes=10, n_clusters=10, n_jobs=1, node2vec=0, node2vec_batchsize=32, node2vec_dim=128, node2vec_epochs=20, node2vec_length=8, node2vec_walk=15, node2vec_windows=3, num_layers=2, order=2, part_iter=50, part_type=5, path='./datasets/data/WSDREAM/', pre_epoch=1000, pretrain=True, processed=0, retrain=0, rounds=1, save_model=1, slice_epochs=60, slices=10, subagg=1, verbose=10, wd=0.0005)
2023-01-17 15:39:47  Experiment start!
2023-01-17 15:39:47  Dataset : rt     interaction : Pure_Mf
2023-01-17 15:39:47  Density : 10.00%, slice_epochs : 60, agg_epochs : 10
2023-01-17 15:39:47  Part_type : 5, 

KeyboardInterrupt: 

In [ ]:
!python Experiment.py --dataset rt --interaction GraphMF --slice_epochs 15 --rounds 1 --agg_epochs 1 --density 0.10 --part_type 5 --debug 1 --agg_function 3

## Dataset : tp

# Desity = 0.10

In [ ]:
!python Experiment.py --dataset tp --interaction NeuCF --rounds 1 --agg_epochs 5 --density 0.10 --part_type 5 --debug 1 --agg_function 3

In [ ]:
!python Experiment.py --dataset tp --interaction CSMF --rounds 1 --agg_epochs 10 --density 0.10 --part_type 5 --debug 1 --agg_function 3

In [ ]:
!python Experiment.py --dataset tp --interaction Pure_Mf --rounds 1 --agg_epochs 10 --density 0.10 --part_type 5 --debug 1 --agg_function 3

In [ ]:
!python Experiment.py --dataset tp --interaction GraphMF --slice_epochs 15 --rounds 1 --agg_epochs 1 --density 0.10 --part_type 5 --debug 1 --agg_function 3